cuda
Traceback (most recent call last):
  File "94.py", line 197, in <module>
    BLEUscore=test(test_loader,i)
  File "94.py", line 184, in test
    references = [references.rstrip()]
AttributeError: 'Tensor' object has no attribute 'rstrip'
cuda
3.6038455753806193 1
3.6506359272426807 2
3.6360791837534947 3
3.6266219477870387 4
3.6287223733744005 5
3.652783392629925 6
3.7316628198149258 7
3.7207821830313113 8
3.6492308639796613 9
3.7438654646547938 10
3.718878249505475 11
3.7312787085412658 12
3.790802145484609 13
3.708292829626499 14
3.8664429005058634 15
3.8086672954654994 16
3.8675183220172777 17
3.838632824064139 18
3.8854461722203237 19
3.787206965334891 20
3.956665882070996 21
3.8783453579466958 22
3.9384943358339997 23
3.85213384483618 24
3.8625171548043196 25
3.768341491846895 26
3.7762008557278426 27
3.8042800456077948 28
3.766315812863183 29
3.7603455005780835 30
3.840138291391219 31
3.77009181474594 32
3.8072082554825797 33
3.6686931176399318 34
3.6249580519331777 35
3.603230291876023 36
3.6703887842823084 37
3.6518960707900474 38
3.6678788546553203 39
3.667390711890713 40
3.6790859360852406 41
3.641862390400034 42
3.653443828047914 43
3.731565126881224 44
3.703789405241616 45
3.6490916365628534 46
3.634218141195503 47
3.6435307410308813 48
3.6510379149813352 49
3.693414848258058 50
3.491718227053234 51
3.5084117267554387 52
3.4901046932551334 53
3.5098740102754267 54
3.5428269889845305 55
3.515734209658049 56
3.518113892189048 57
3.5114190042003144 58
3.5100860068917368 59
3.461102245811848 60
3.5783946440755576 61
3.547968704644072 62
3.5213516913786793 63
3.477070626639869 64
3.5072316141880067 65
3.509052617683928 66
3.4959753726514182 67
3.455876556579872 68
3.490184953778617 69
3.5025817445270517 70
3.520213424155367 71
3.498545351611702 72
3.47317524891564 73
3.519216947569856 74
3.509351679773061 75
3.5129853120804166 76
3.4516166659851946 77
3.509487759502313 78
3.5016512117145804 79
3.489406412443186 80
3.501672832204286 81
3.5204340880394565 82
3.525422382456727 83
3.5594656035233716 84
3.510002847683155 85
3.481722420992887 86
3.510990587523477 87
3.551019808896869 88
3.55694721237073 89
3.481973859257479 90
3.499621839997778 91
3.527798792981095 92
3.496371620709671 93
3.495195998487344 94
3.488172854236792 95
3.5437470417892345 96
3.4806634686074696 97
3.5018106965738 98
3.5318179705573165 99
Traceback (most recent call last):
  File "94.py", line 204, in <module>
    fig = plt.figure()
NameError: name 'plt' is not defined
